# SCHEMAT:
# fraza z nazwy produktu: ['Nazwa cechy w MM', domyślna waga, 'Nazwa cechy w MM dla drugiego typu']
attributes_sets = {
    'depilat': ['Depilatory'],
    'deskorol': ['Deskorolki', 5],
    'hdd': ['Dyski HDD'],
    'ssd': ['Dyski SSD'],
    'gra': ['Gry'],
    'applewatch': ['Inteligentne zegarki i opaski > Applewatch'],
    'smartwatch': ['Inteligentne zegarki i opaski > Smartwatche'],
    'smartphone': ['Telefony i smartfony > Smartfony z Android'],
    'smartfon': ['Telefony i smartfony > Smartfony z Android'],
    'zegarek sportowy': ['Inteligentne zegarki i opaski > Zegarki Sportowe'],
    'laptop': ['Laptopy / Ultrabooki', 5],
    'ultrabook': ['Laptopy / Ultrabooki', 5],
    'lodów': ['Lodówki', 50, 'Lodówki do zabudowy'],
    'maszynka': ['Maszynki do strzyżenia'],
    'tablet': ['Tablety'],
    'telewiz': ['Telewizory', 15],
    'słuchaw': ['Słuchawki'],
    'mikrofal': ['Kuchnie mikrofalowe', 15, 'Kuchenki mikrofalowe do zabudowy'],
    'kuchn': ['Kuchnie wolnostojące > Kuchnie', 50, 'Kuchnie do zabudowy'],
    'piekarnik': ['', 1, 'Piekarniki do zabudowy'],
    'pralka': ['Pralki', 40, 'Pralki do zabudowy'],
    'płyta': ['', 1, 'Płyty do zabudowy'],
    'pralko-': ['Pralko-suszarki', 40],
    'suszarka': ['Suszarka spożywcza', 40],
    'zamraż': ['Zamrażarki', 50, 'Zamrażarki do zabudowy'],
    'zmywar': ['Zmywarki', 30],
    'okap': ['Okapy', 15]
}
